version: 2.1

orbs:
  python: circleci/python@0.2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    working_directory: /app
    docker:
      - image: thushv89/attention-keras:tf-1.15.2
    steps:
      - checkout
      - run:
          command: |
            cd /app/src
            pytest
